### ISSUE TITLE
Enmasse script not working on 1.1 release

### ISSUE THREAD

**Issue by ivaano** [zatosource/zato#309]
I've downloaded the enmasse script from https://zato.io/docs/admin/guide/enmasse.html, I've also tried all the commits from current source ~/git/zato/code/zato-cli/src/zato/cli/enmasse.py none of them work on 1.1 newer ones use NTLM, this are the commits I've tried:

commit 7ee41990e92657412958d839ec82373b6337d13f
commit 0ab4ccc11f042cd5002373cf653d43ac05fe9540
commit 9fcf0f0ad8dd437ce0eb8c90ccbad50ab38ca678
commit ee220d6ecf2a8ae9e2a253a361cafa0f703ca464
commit d5b0059f375ae6fa1dbdcf6d6e59b130bd9f6c2f
commit f3d0233cdb8ee4eef2fa8555350106cde1d4e8f5
commit b6d4243ecd082a8212963f163789f7e55c6985a2
commit cc1c9058f0b728e26648f4e9091504a6090d6d94
commit bfdcdb72d61d63bc7d605ee6e2305cb940e66772
commit 5fb974cde0e7101f837dcf30504f7b01650fbd0b
commit 321266cd8aa225525c660f48ce5a1a15d84c860f
commit 25f657b44ae253832e0b0b8213c41641125c7ddc
commit 80877c7f75e51e253af409f069108d00013dbfef
commit 18743a86c514f9047e9531aaf84d0c3cea14fc5f
commit 1e5f0546bb4eae3caf206e21abb46cbfdea708c4
commit 534e099e59ed9dbfa8cba9417712a34a706e91e1
commit 3139f88f1ac6a8850e58dee167504e0c538e1357
commit 1091a224ef53395876cb365cb90e46d36b9b2e41
commit ee6d66dcbbcec35dc1dc1af186d93a4d44d637ee
commit f525bc5f1da54584e43538d468d92c9061bb21c8

zato@esb-stage:~$ py enmasse
Traceback (most recent call last):
  File "/opt/zato/1.1/bin/py", line 106, in <module>
    execfile(__file__)
  File "enmasse", line 40, in <module>
    from zato.common.odb.model import ConnDefAMQP, ConnDefWMQ, HTTPBasicAuth, \
ImportError: cannot import name OAuth

**Comment by dsuch** [comment]
Fixed in 2.0 - please re-open if it ever happens again. Thanks!
